version: 2

models:
  - name: int_contacts
    description: RDS + Hubspot contact information
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: ref("sample_int")
    columns:
      - name: contact_pk
        tests:
          - dbt_expectations.expect_column_values_to_be_unique:
              row_condition: "contact_pk is not null" # (Optional)
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: phone
        tests:
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: '^\(\d{3}\) \d{3}-\d{4}$'
              row_condition: "phone is not null"